//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Владелец.
    /// </summary>
    //  *** Start programmer edit section *** (Владелец CustomAttributes)

    //  *** End programmer edit section *** (Владелец CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВладелецE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ВладелецL", new string[] {
            "Наименование"})]
    public class Владелец : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        //  *** Start programmer edit section *** (Владелец CustomMembers)

        //  *** End programmer edit section *** (Владелец CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Владелец.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Владелец.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Владелец.Наименование Get start)

                //  *** End programmer edit section *** (Владелец.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Владелец.Наименование Get end)

                //  *** End programmer edit section *** (Владелец.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Владелец.Наименование Set start)

                //  *** End programmer edit section *** (Владелец.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Владелец.Наименование Set end)

                //  *** End programmer edit section *** (Владелец.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВладелецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецE", typeof(IIS.Test.Владелец));
                }
            }
            
            /// <summary>
            /// "ВладелецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецL", typeof(IIS.Test.Владелец));
                }
            }
        }
    }
}
