//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Робот.
    /// </summary>
    //  *** Start programmer edit section *** (Робот CustomAttributes)

    //  *** End programmer edit section *** (Робот CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Робот", new string[] {
            "Имя",
            "Владелец",
            "Владелец.Наименование"})]
    [View("РоботE", new string[] {
            "Имя as \'Имя\'",
            "Владелец as \'Владелец\'",
            "Владелец.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Владелец.Наименование"})]
    [MasterViewDefineAttribute("РоботE", "Владелец", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("РоботL", new string[] {
            "Имя as \'Имя\'",
            "Владелец.Наименование as \'Наименование\'"})]
    public class Робот : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private IIS.Test.Владелец fВладелец;
        
        //  *** Start programmer edit section *** (Робот CustomMembers)

        //  *** End programmer edit section *** (Робот CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        //  *** Start programmer edit section *** (Робот.Имя CustomAttributes)

        //  *** End programmer edit section *** (Робот.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                //  *** Start programmer edit section *** (Робот.Имя Get start)

                //  *** End programmer edit section *** (Робот.Имя Get start)
                string result = this.fИмя;
                //  *** Start programmer edit section *** (Робот.Имя Get end)

                //  *** End programmer edit section *** (Робот.Имя Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Робот.Имя Set start)

                //  *** End programmer edit section *** (Робот.Имя Set start)
                this.fИмя = value;
                //  *** Start programmer edit section *** (Робот.Имя Set end)

                //  *** End programmer edit section *** (Робот.Имя Set end)
            }
        }
        
        /// <summary>
        /// Робот.
        /// </summary>
        //  *** Start programmer edit section *** (Робот.Владелец CustomAttributes)

        //  *** End programmer edit section *** (Робот.Владелец CustomAttributes)
        [NotNull()]
        public virtual IIS.Test.Владелец Владелец
        {
            get
            {
                //  *** Start programmer edit section *** (Робот.Владелец Get start)

                //  *** End programmer edit section *** (Робот.Владелец Get start)
                IIS.Test.Владелец result = this.fВладелец;
                //  *** Start programmer edit section *** (Робот.Владелец Get end)

                //  *** End programmer edit section *** (Робот.Владелец Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Робот.Владелец Set start)

                //  *** End programmer edit section *** (Робот.Владелец Set start)
                this.fВладелец = value;
                //  *** Start programmer edit section *** (Робот.Владелец Set end)

                //  *** End programmer edit section *** (Робот.Владелец Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Робот" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Робот
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Робот", typeof(IIS.Test.Робот));
                }
            }
            
            /// <summary>
            /// "РоботE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РоботE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РоботE", typeof(IIS.Test.Робот));
                }
            }
            
            /// <summary>
            /// "РоботL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РоботL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РоботL", typeof(IIS.Test.Робот));
                }
            }
        }
    }
}
